### ISSUE TITLE
Infinite loops on CVODE

### ISSUE THREAD

**Issue by Sangung** [aseyboldt/sunode#25]
Hi. I have suffered the same problem (infinite loops on CVODE) as you in this post, (https://githubmemory.com/repo/LLNL/sundials/issues/44)

(The interesting point to add is that, sometimes it gets certain values after taking plenty of times...)

Is there any update on this problem? 

I have used the version:
pymc3                     3.9.3,
sunode                    0.1.1, and
sundials                   5.3.0
 
If there is an update on this problem, I plan to update the newest version.

**Comment by aseyboldt** [comment]
I think this was fixed in sundials 5.4.0 and I've never seen that behaviour since.

**Comment by Sangung** [comment]
> I think this was fixed in sundials 5.4.0 and I've never seen that behaviour since.

Thank you for your comments! I will update my version and see if I suffer from the same problem.
