### ISSUE TITLE
Only works with conda

### ISSUE THREAD

**Issue by lmarti** [aseyboldt/sunode#3]
There are hard-codes dependencies that force to use conda. For example, here: [build_cvodes.py](https://github.com/aseyboldt/sunode/blob/master/sunode/build_cvodes.py)

**Comment by aseyboldt** [comment]
True.
It shouldn't be hard to get rid of the explicit conda requirement if the user wants to deal with all the search paths on their own. Pip support is a bit more tricky I think.
I have to figure out where the sundials libs should come from then (system installed, distributed as part of the package?). Same for blas and possibly klu.
Using conda makes all of this much easier.
