### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by michaelosthege** [aseyboldt/sunode#30]
The license file (MIT) and the license specified in `meta.yml` (Apache 2) don't match.

@aseyboldt which one is correct?

**Comment by aseyboldt** [comment]
Oh...
Do you have preferences? I don't really know which I prefer.
But maybe we should specify both now, if they were there at some point?

**Comment by michaelosthege** [comment]
Let's stick with MIT then, since it was more prominent in the repo and it's also simpler
