### ISSUE TITLE
Sunode on linux-aarch64

### ISSUE THREAD

**Issue by Dragomordor** [aseyboldt/sunode#54]
Hi, I would like to know if it is possible for sunode to be installed and used on linux-aarch64, as it is not mentioned in the conda forge environments?

**Comment by maresb** [comment]
Hey @Dragomordor! I'm not sure, let's give it a try. I opened https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6148 so in some hours after it's merged it will hopefully set things in motion to attempt a linux-aarch64 build.

**Comment by Dragomordor** [comment]
Awesome! Thanks for the swift response.

I'm attempting to leverage an Oracle Cloud server which uses aarch64, so it would be fantastic if it does work.

**Comment by maresb** [comment]
The conda-forge automigration infrastructure is a bit stalled on https://github.com/conda-forge/mkl-service-feedstock/pull/33 so I'm giving it a try by hand in https://github.com/conda-forge/sunode-feedstock/pull/36.

**Comment by maresb** [comment]
This should be available on conda-forge within a few hours.

**Comment by Dragomordor** [comment]
This seems to be working without any hiccups. Thank you for taking the time to make this happen!

**Comment by maresb** [comment]
Excellent, thanks so much @Dragomordor for reporting back!
